version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    tty: false
    stdin_open: false
    ports:
      - "25565:25565"
    environment:
      MEMORY: "2G"
      VERSION: "1.18.2"
      EULA: "TRUE"
      TYPE: FORGE
      CF_SERVER_MOD: /modpacks/Create-Astral-v2.0.5b.zip
      # ENABLE_AUTOPAUSE: "TRUE"
      # AUTOPAUSE_TIMEOUT_INIT: "30"
      # AUTOPAUSE_TIMEOUT_EST: "30"
      # miecraft server properties
      ALLOW_FLIGHT: "true"
      OPS: "chieforz"
      WHITELIST: "chieforz"
      ENFORCE_WHITELIST: "true"
    volumes:
      - data:/data
      - ./modpacks:/modpacks:ro

volumes:
  data: {}