version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    tty: false
    stdin_open: false
    ports:
      - "25565:25565"
    environment:
      MEMORY: "3G"
      VERSION: "1.18.2"
      EULA: "TRUE"
      TYPE: "AUTO_CURSEFORGE"
      CF_API_KEY: "$$2a$$10$$W6kRsnNBSH3kQfwAtOJ8zuoovVSaIJAi4Ra2zOQv0AdkuJBhR7m8i"
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/create-astral"
      ENABLE_AUTOPAUSE: "TRUE"
      AUTOPAUSE_TIMEOUT_INIT: "30"
      AUTOPAUSE_TIMEOUT_EST: "30"
    volumes:
      # attach the relative directory 'minecraft-data' to the container's /data path
      - ~/minecraft-data:/data